version: "1.0"
info:
  model: int-scaffold
packages:
- name: SiqaGitMCSPPP2807Project
  gitServerName: Kusi_MCSPPP
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqagitmcsppp2807.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBNewInsert
  packages:
  - name: SiqaGitMCSPPP2807Project
    version: "1.0"
- serviceName: project.siqagitmcsppp2807.integrations:SIQAAdapterFlow
  packages:
  - name: SiqaGitMCSPPP2807Project
    version: "1.0"
